### ISSUE TITLE
SiteRM Raise condition if switch is down.

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#253]
SiteRM workflow is:
In case a new start process (LookUP, Provisioning), get ansible output; After that, follows:
1. Every hour (+-5m random) - get on the switch and get ansible output. Save this output to DB;
2. Reuse this ansible output in a Model generation and PolicyService comparison. (We are not getting to switch every 30s to check that config equals).
3. If delta is received - ansible is forced to get output from the switch, compare it, apply what is needed, and go back to 1.

Raise the condition below, and force update should be used update only if successful. So if it fails - it should continue to get back and communicate with switch (without changing model)
```
Fri, 03 Mar 2023 06:06:24.468 - LookUpService - INFO - Forcefully update the model in db as it is older than 1h
Fri, 03 Mar 2023 06:06:34.506 - LookUpService - INFO - Start worker for NRM_CENIC site
Fri, 03 Mar 2023 06:06:34.516 - LookUpService - INFO - Started LookupService work
Fri, 03 Mar 2023 06:08:35.227 - LookUpService - CRITICAL - Exception!!! Error details:  Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/DTNRMSiteFE-1.1.0-py3.9.egg/DTNRMLibs/Daemonizer.py", line 244, in run
    rthread.startwork()
  File "/usr/lib/python3.9/site-packages/DTNRMSiteFE-1.1.0-py3.9.egg/SiteFE/LookUpService/lookup.py", line 133, in startwork
    self.addSwitchInfo(self.renewSwitchConfig)
  File "/usr/lib/python3.9/site-packages/DTNRMSiteFE-1.1.0-py3.9.egg/SiteFE/LookUpService/modules/switchinfo.py", line 316, in addSwitchInfo
    switchInfo = self.switch.getinfo(renew)
  File "/usr/lib/python3.9/site-packages/DTNRMSiteFE-1.1.0-py3.9.egg/DTNRMLibs/Backends/main.py", line 223, in getinfo
    raise Exception('Failed ANSIBLE Runtime. See Error %s' % str(err))
Exception: Failed ANSIBLE Runtime. See Error {'aristaeos_s0': [{}, {}, {}, {'msg': 'ssh connection failed: ssh connect failed: Timeout connecting to X X X X', 'invocation': {'module_args': {'gather_subset': ['all'], 'available_network_resources': False, 'gather_network_resources': None}}, '_ansible_no_log': None, 'changed': False}]}

Fri, 03 Mar 2023 06:08:45.244 - LookUpService - INFO - Had Runtime Failure. Sleep for 30 seconds
Fri, 03 Mar 2023 06:09:15.285 - LookUpService - INFO - Start worker for NRM_CENIC site
Fri, 03 Mar 2023 06:09:15.295 - LookUpService - INFO - Started LookupService work
Fri, 03 Mar 2023 06:09:38.731 - LookUpService - INFO - Checking if a new model is different from previous
Fri, 03 Mar 2023 06:09:38.788 - LookUpService - INFO - Models are different. Update DB
Fri, 03 Mar 2023 06:09:48.839 - LookUpService - INFO - Start worker for NRM_CENIC site
Fri, 03 Mar 2023 06:09:48.851 - LookUpService - INFO - Started LookupService work
Fri, 03 Mar 2023 06:10:24.481 - LookUpService - INFO - Checking if a new model is different from previous
Fri, 03 Mar 2023 06:10:24.619 - LookUpService - INFO - Models are equal.
Fri, 03 Mar 2023 06:10:34.667 - LookUpService - INFO - Start worker for NRM_CENIC site
Fri, 03 Mar 2023 06:10:34.677 - LookUpService - INFO - Started LookupService work
Fri, 03 Mar 2023 06:11:09.502 - LookUpService - INFO - Checking if new model is different from previous
Fri, 03 Mar 2023 06:11:09.669 - LookUpService - INFO - Models are equal.
```

**Comment by juztas** [comment]
Error is here: https://github.com/sdn-sense/siterm/blob/master/src/python/DTNRMLibs/Backends/main.py#L221 and because https://github.com/sdn-sense/siterm/blob/master/src/python/SiteFE/ProvisioningService/provisioningService.py#L133 is False. If LookUp gets ansible out (even failure, means empty dict), fails because err. Continue to fail while unable to communicate. 
Once it is able to communicate, Provisioning and LookUpService are separate processes, so DB is empty, and Policy Service deletes vlan (as it is not in the model anymore).

Need to move err raise before writing to DB.

**Comment by juztas** [comment]
Solved here: https://github.com/sdn-sense/siterm/pull/254
