### ISSUE TITLE
[Dev-Release-Issue] Broken vlan id identification

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#392]
Dev changes - added before the break, broke FE to identify vlan id:
https://github.com/sdn-sense/siterm/commit/faed04968cb2c80c9f85af81d73161af108d0646
```
Tue, 02 Jan 2024 16:06:10.490 - LookUpService - CRITICAL - Exception!!! Error details:  Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/SiteRMSiteFE-1.3.12-py3.9.egg/SiteRMLibs/Daemonizer.py", line 270, in run
    rthread.startwork()
  File "/usr/lib/python3.9/site-packages/SiteRMSiteFE-1.3.12-py3.9.egg/SiteFE/LookUpService/lookup.py", line 158, in startwork
    self.addNodeInfo()
  File "/usr/lib/python3.9/site-packages/SiteRMSiteFE-1.3.12-py3.9.egg/SiteFE/LookUpService/modules/nodeinfo.py", line 56, in addNodeInfo
    self.defineHostInfo(nodeDict, nodeDict['hostinfo'])
  File "/usr/lib/python3.9/site-packages/SiteRMSiteFE-1.3.12-py3.9.egg/SiteFE/LookUpService/modules/nodeinfo.py", line 306, in defineHostInfo
    vtype='vlanport', vlan=vlanNameSpl[1])
IndexError: list index out of
```

**Comment by juztas** [comment]
https://github.com/sdn-sense/siterm/pull/394
