### ISSUE TITLE
Debugger catch any errors in debugger and log to log file

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#477]
For example if gateway is not valid hostname:
```
Tue, 19 Mar 2024 03:02:11.717 - SiteRM-Background-Process-Runner - CRITICAL - Exception!!! Error details:  Traceback (most recent call last):
  File "/usr/lib64/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib64/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/lib64/python3.9/http/client.py", line 946, in connect
    self.sock = self._create_connection(
  File "/usr/lib64/python3.9/socket.py", line 823, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```
Also it should check if file is open
```

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/SiteRMSiteFE-1.3.12-py3.9.egg/SiteRMLibs/Daemonizer.py", line 421, in run
    rthread.startwork()
  File "/usr/lib/python3.9/site-packages/SiteRMSiteFE-1.3.12-py3.9.egg/SiteRMLibs/BaseDebugAction.py", line 68, in startwork
    self.processout.wn(f"====== {self.service} Finish Work. Config: {self.backgConfig}")
  File "/usr/lib/python3.9/site-packages/SiteRMSiteFE-1.3.12-py3.9.egg/SiteRMLibs/BaseDebugAction.py", line 21, in wn
    self.fd.write(inline)
ValueError: I/O operation on closed file.
```

**Comment by juztas** [comment]
https://github.com/sdn-sense/siterm/pull/482
