### ISSUE TITLE
Use threading for switches get config/apply config

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#487]
Currently Siterm does access switches in seq, and that might delay things. e.g. Seen several cases, where having multiple devices under one Siterm - needs to wait for all ansible runs to finish. We could parallelize access to devices - so that can run faster.

**Comment by juztas** [comment]
https://github.com/sdn-sense/siterm/pull/534

**Comment by juztas** [comment]
Threading enabled for retrieval of switch information. Deployed on CaltechTier2/SDN, LAArista, PRP. Tested few paths - looks all correct. 

Need to test if it affects RAW plugin (e.g. Opennsa)

**Comment by juztas** [comment]
```
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/siterm-states/SwitchWorker.json.tmp' -> '/tmp/siterm-states/SwitchWorker.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/SiteRMSiteFE-1.4.3-py3.9.egg/SiteRMLibs/Daemonizer.py", line 439, in run
    self.reporter('OK', sitename, stwork)
  File "/usr/lib/python3.9/site-packages/SiteRMSiteFE-1.4.3-py3.9.egg/SiteRMLibs/Daemonizer.py", line 369, in reporter
    self.contentDB.dumpFileContentAsJson(
  File "/usr/lib/python3.9/site-packages/SiteRMSiteFE-1.4.3-py3.9.egg/SiteRMLibs/MainUtilities.py", line 396, in dumpFileContentAsJson
    shutil.move(tmpoutFile, outFile)
  File "/usr/lib64/python3.9/shutil.py", line 845, in move
    copy_function(src, real_dst)
  File "/usr/lib64/python3.9/shutil.py", line 444, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/siterm-states/SwitchWorker.json.tmp'

```

**Comment by juztas** [comment]
```
Mon, 03 Jun 2024 07:06:18.719 - SwitchWorker - CRITICAL - Exception!!! Error details:  Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/SiteRMSiteFE-1.4.3-py3.9.egg/SiteRMLibs/Daemonizer.py", line 438, in run
    rthread.startwork()
  File "/usr/lib/python3.9/site-packages/SiteRMSiteFE-1.4.3-py3.9.egg/SiteFE/LookUpService/SwitchWorker.py", line 32, in startwork
    self.lookup.startworkrenew([self.device])
  File "/usr/lib/python3.9/site-packages/SiteRMSiteFE-1.4.3-py3.9.egg/SiteFE/LookUpService/lookup.py", line 308, in startworkrenew
    self.switch.getinfoNew(hosts)
  File "/usr/lib/python3.9/site-packages/SiteRMSiteFE-1.4.3-py3.9.egg/SiteRMLibs/Backends/main.py", line 316, in getinfoNew
    out, err = self.plugin._getFacts(hosts)
  File "/usr/lib/python3.9/site-packages/SiteRMSiteFE-1.4.3-py3.9.egg/SiteRMLibs/Backends/Ansible.py", line 122, in _getFacts
    ansOut = self._executeAnsible("getfacts.yaml", hosts, subitem)
  File "/usr/lib/python3.9/site-packages/SiteRMSiteFE-1.4.3-py3.9.egg/SiteRMLibs/Backends/Ansible.py", line 74, in _executeAnsible
    return ansible_runner.run(
  File "/usr/local/lib/python3.9/site-packages/ansible_runner/interface.py", line 213, in run
    r.run()
  File "/usr/local/lib/python3.9/site-packages/ansible_runner/runner.py", line 148, in run
    cleanup_artifact_dir(os.path.join(self.config.artifact_dir, ".."), self.config.rotate_artifacts)
  File "/usr/local/lib/python3.9/site-packages/ansible_runner/utils/__init__.py", line 182, in cleanup_artifact_dir
    shutil.rmtree(all_paths[f])
  File "/usr/lib64/python3.9/shutil.py", line 734, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib64/python3.9/shutil.py", line 667, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib64/python3.9/shutil.py", line 690, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib64/python3.9/shutil.py", line 688, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: '6-15d809b6-25a9-4431-a387-1756eefb04ab.json'

```

**Comment by juztas** [comment]
https://github.com/sdn-sense/siterm/pull/539

**Comment by juztas** [comment]
Already in prod on multiple sites. Some item is an interest to test out:
1. Run latest version on Caltech dev (with 1 switch) and record delta timings; Run 5 in parallel and record total runtime;
2. Run latest version on Caltech dev (with 2 switch) and record delta timings; Run 5 in parallel and record total runtime;
3. Run latest version on Caltech dev (with 3 switch) and record delta timings; Run 5 in parallel and record total runtime;
4. Run latest version on Caltech dev (with 4 switch) and record delta timings; Run 5 in parallel and record total runtime;

Repeat same tests with new dev release.
