### ISSUE TITLE
In case of AnsiblePrepare failure - fail/not start all services

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#523]
```
/root/ansible-prepare.py
Traceback (most recent call last):
  File "/root/ansible-prepare.py", line 190, in <module>
    generateAnsible()
  File "/root/ansible-prepare.py", line 185, in generateAnsible
    inventory = getYamlContent("/etc/ansible-conf.yaml", True)
  File "/root/ansible-prepare.py", line 62, in getYamlContent
    out = yaml.safe_load(fd.read())
  File "/usr/local/lib64/python3.9/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib64/python3.9/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib64/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib64/python3.9/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib64/python3.9/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib64/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib64/python3.9/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib64/python3.9/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib64/python3.9/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 4, column 1:
    inventory:
    ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 17, column 2:
     edgecore_s0:
     ^
```

**Comment by juztas** [comment]
https://github.com/sdn-sense/siterm-startup/commit/e8680e9e3a4839b22c6332953d7ad1bd59fa9d73
