### ISSUE TITLE
fe unable to write switch backend after next day rollout

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#552]
```
[Sat Jun 08 01:09:10.448699 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374] Traceback (most recent call last):
[Sat Jun 08 01:09:10.448745 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]   File "/var/www/wsgi-scripts/sitefe.wsgi", line 4, in <module>
[Sat Jun 08 01:09:10.448749 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]     from SiteFE.REST.app import Frontend
[Sat Jun 08 01:09:10.448755 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]   File "/usr/local/lib/python3.9/site-packages/SiteFE/REST/app.py", line 26, in <module>
[Sat Jun 08 01:09:10.448758 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]     from SiteFE.REST.Modules.DeltaCalls import DeltaCalls
[Sat Jun 08 01:09:10.448763 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]   File "/usr/local/lib/python3.9/site-packages/SiteFE/REST/Modules/DeltaCalls.py", line 24, in <module>
[Sat Jun 08 01:09:10.448766 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]     from SiteFE.PolicyService import policyService as polS
[Sat Jun 08 01:09:10.448771 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]   File "/usr/local/lib/python3.9/site-packages/SiteFE/PolicyService/policyService.py", line 25, in <module>
[Sat Jun 08 01:09:10.448774 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]     from SiteRMLibs.Backends.main import Switch
[Sat Jun 08 01:09:10.448779 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]   File "/usr/local/lib/python3.9/site-packages/SiteRMLibs/Backends/main.py", line 11, in <module>
[Sat Jun 08 01:09:10.448782 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]     from SiteRMLibs.Backends.Ansible import Switch as Ansible
[Sat Jun 08 01:09:10.448787 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]   File "/usr/local/lib/python3.9/site-packages/SiteRMLibs/Backends/Ansible.py", line 18, in <module>
[Sat Jun 08 01:09:10.448790 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]     from SiteRMLibs.Backends import parsers
[Sat Jun 08 01:09:10.448795 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]   File "/usr/local/lib/python3.9/site-packages/SiteRMLibs/Backends/parsers/__init__.py", line 24, in <module>
[Sat Jun 08 01:09:10.448798 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]     _tmp = tmpMod.MODULE(config=config)
[Sat Jun 08 01:09:10.448803 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]   File "/usr/local/lib/python3.9/site-packages/SiteRMLibs/Backends/parsers/default.py", line 30, in __init__
[Sat Jun 08 01:09:10.448806 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]     self.logger = getLoggingObject(config=kwargs['config'], service='SwitchBackends')
[Sat Jun 08 01:09:10.448811 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]   File "/usr/local/lib/python3.9/site-packages/SiteRMLibs/MainUtilities.py", line 137, in getLoggingObject
[Sat Jun 08 01:09:10.448814 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]     return getTimeRotLogger(**kwargs)
[Sat Jun 08 01:09:10.448819 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]   File "/usr/local/lib/python3.9/site-packages/SiteRMLibs/MainUtilities.py", line 157, in getTimeRotLogger
[Sat Jun 08 01:09:10.448821 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]     handler = logging.handlers.TimedRotatingFileHandler(
[Sat Jun 08 01:09:10.448826 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]   File "/usr/lib64/python3.9/logging/handlers.py", line 211, in __init__
[Sat Jun 08 01:09:10.448829 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]     BaseRotatingHandler.__init__(self, filename, 'a', encoding=encoding,
[Sat Jun 08 01:09:10.448835 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]   File "/usr/lib64/python3.9/logging/handlers.py", line 58, in __init__
[Sat Jun 08 01:09:10.448837 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]     logging.FileHandler.__init__(self, filename, mode=mode,
[Sat Jun 08 01:09:10.448842 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]   File "/usr/lib64/python3.9/logging/__init__.py", line 1146, in __init__
[Sat Jun 08 01:09:10.448845 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]     StreamHandler.__init__(self, self._open())
[Sat Jun 08 01:09:10.448850 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]   File "/usr/lib64/python3.9/logging/__init__.py", line 1175, in _open
[Sat Jun 08 01:09:10.448853 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374]     return open(self.baseFilename, self.mode, encoding=self.encoding,
[Sat Jun 08 01:09:10.448867 2024] [wsgi:error] [pid 59829:tid 140138426402560] [remote 10.244.1.4:33374] PermissionError: [Errno 13] Permission denied: '/var/log/siterm-site-fe/SwitchBackends/api.log
```

**Comment by juztas** [comment]
https://github.com/sdn-sense/siterm/pull/556
