### ISSUE TITLE
DBCleaner no refreshthread

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#603]
```
Mon, 12 Aug 2024 17:54:30.995 - DBCleaner - CRITICAL - Exception!!! Error details:  Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/SiteRMLibs/Daemonizer.py", line 409, in refreshThreads
    self.getThreads()
  File "/usr/local/bin/DBCleaner-service", line 27, in getThreads
    self.runThreads[sitename].refreshthread()
AttributeError: 'DBCleaner' object has no attribute 'refreshthread'

```

**Comment by juztas** [comment]
https://github.com/sdn-sense/siterm/pull/604
