### ISSUE TITLE
unable to insert switch error to db, if switch never ran successfully. 

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#612]
```
Thu, 12 Sep 2024 00:00:35.402 - SwitchWorker - CRITICAL - Exception!!! Error details:  Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/SiteRMLibs/Daemonizer.py", line 436, in run
    rthread.startwork()
  File "/usr/local/lib/python3.9/site-packages/SiteFE/LookUpService/SwitchWorker.py", line 44, in startwork
    self.switch.getinfoNew(self.device)
  File "/usr/local/lib/python3.9/site-packages/SiteRMLibs/Backends/main.py", line 318, in getinfoNew
    self._insertErrToDB(err)
  File "/usr/local/lib/python3.9/site-packages/SiteRMLibs/Backends/main.py", line 212, in _insertErrToDB
    self.dbI.insert("switch_error", [out])
  File "/usr/local/lib/python3.9/site-packages/SiteRMLibs/DBBackend.py", line 229, in insert
    out = self.db.execute_ins(self.getcall('insert', calltype), values)
  File "/usr/local/lib/python3.9/site-packages/SiteRMLibs/DBBackend.py", line 182, in getcall
    raise ex
  File "/usr/local/lib/python3.9/site-packages/SiteRMLibs/DBBackend.py", line 179, in getcall
    callquery = getattr(dbcalls, f'{callaction}_{calltype}')
AttributeError: module 'SiteRMLibs.dbcalls' has no attribute 'insert_switch_error'
```

**Comment by juztas** [comment]
https://github.com/sdn-sense/siterm/commit/e18bf4554d812c715c6578ab12df8bc34ba3dc54
